FROM ruby:2.5.7
ARG GIT_COMMIT=undefined
RUN mkdir /app
WORKDIR /app
RUN useradd -m appuser
COPY Gemfile /app
COPY Gemfile.lock /app
RUN gem install bundler
RUN bundler install
COPY . /app
LABEL GIT_COMMIT=$GIT_COMMIT
RUN chown -R appuser:appuser /app
USER appuser
CMD ["/app/start_app.sh"]
